# Generated by Django 4.2.11 on 2024-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_shortenedurl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_url',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
